### ISSUE TITLE
Documentation: How to install a seccomp profile

### ISSUE THREAD

**Issue by CodeClinch** [karydia/karydia#135]
### Description
The seccomp profile "docker/default" is available on Kubernetes hosts. With Karydia it is possible to select also other profiles. How could the profiles be installed on a node? The solution should be described.

### User Story

As _a user_ I want to _use a custom seccomp profile_ in order to _restrict the access to the node_.

**Comment by Neumann-Nils** [comment]
### How to use custom seccomp profile with Docker
1. Create your own custom seccomp profile (this one allows all syscalls except `chmod`):
```
{
	"defaultAction": "SCMP_ACT_ALLOW",
	"architectures": [
		"SCMP_ARCH_X86_64",
		"SCMP_ARCH_X86",
		"SCMP_ARCH_X32"
	],
	"syscalls": [
		{
			"names": [
				"chmod"
			],
			"action": "SCMP_ACT_ERRNO",
			"args": [],
			"comment": "",
			"includes": {},
			"excludes": {}
		}
	]
}
```
More examples can be found here:
- https://github.com/moby/moby/blob/master/profiles/seccomp/default.json
- https://github.com/docker/labs/tree/master/security/seccomp/seccomp-profiles

2. Run an docker container with the created seccomp profile
```
docker container run -it --rm --security-opt seccomp=test_seccomp.json alpine sh
```

3. Test the seccomp profile (e.g. try out blocked syscalls)

**Comment by Neumann-Nils** [comment]
Main open question:
- How to place a custom seccomp profile on the nodes?
