### ISSUE TITLE
Helm Chart with Feature Options

### ISSUE THREAD

**Issue by CodeClinch** [karydia/karydia#144]
### Description
It should be possible to select or deselect each feature in the helm values file.

https://github.com/karydia/karydia/blob/master/install/charts/templates/deployment.yaml
Options:
- --enable-default-network-policy
- --enable-karydia-admission
 - --enable-opa-admission

### User Story

As _a user_ I want to _decided which feature should be used_ in order to _have the possibility to use Karydia with a selected set of features_.

**Comment by Neumann-Nils** [comment]
Fixed with #147.
