### ISSUE TITLE
Add annotation to namespace if network policy is assigned automatically

### ISSUE THREAD

**Issue by CodeClinch** [karydia/karydia#173]
If a namespace does not have an annotation that specifies a network policy the system should add the default network policy and adds the annotation.

- [x] what is the best way to add this annotation (webhook or reconciler for networkpolicy namespace)
- [x] Implementation

**Comment by marcrahnsap** [comment]
Wouldn't it be better to annotate the network policy resource with the source of the security setting?

**Comment by CodeClinch** [comment]
You are right. It fits better to the network policy.

**Comment by Neumann-Nils** [comment]
Should be solved in #179.
