### ISSUE TITLE
Karydia cannot be installed

### ISSUE THREAD

**Issue by CodeClinch** [karydia/karydia#182]
### Description

I tried to install karydia, but it crashes. 

### Steps to reproduce
1. kubectl apply -f ./install/helm-service-account.yaml
2. helm init --service-account tiller
3. helm install ./install/charts --name karydia
4.  kubectl get pods -n kube-system

### Expected behavior

Karydia pod should be running. But it has status error.

### Logs / console output / screenshots / affected lines of code

Failed to load KarydiaDefaultNetworkPolicy : karydianetworkpolicies.karydia.gardener.cloud "kube-system:karydia-default-network-policy" is forbidden: User "system:serviceaccount:kube-system:karydia" cannot get resource "karydianetworkpolicies" in API group "karydia.gardener.cloud" at the cluster scope

### Environment

- Kubernetes version (use `kubectl version`): 
- Cloud provider or hardware configuration: 
- [x] Gardener cluster
- OS (e.g. `cat /etc/os-release` OR `sw_vers`): 
- Kernel (e.g. `uname -a`): 
- Others:

**Comment by SAPJonasZengerle** [comment]
Tried to reproduce the described behaviour but I couldn't - for me it just works! 😎 

[latest on `master` branch (9ac68eecc945fd39e0a8369473f9191e62825f04); kubectl version (client & server): v1.15.2]

**Comment by CodeClinch** [comment]
After pulling the latest code changes it was working.
