### ISSUE TITLE
Remove all artifacts on delete

### ISSUE THREAD

**Issue by CodeClinch** [karydia/karydia#184]
### Description

When Karydia is deleted some artifacts are still in the system
* Web hooks
* Custom resource definition

### Steps to reproduce
1. Delete Karydia
2. Check for artifacts

### Expected behavior

Al artifacts should be deleted

### Environment

- Kubernetes version (use `kubectl version`): 
- Cloud provider or hardware configuration: 
- [x] Gardener cluster
- OS (e.g. `cat /etc/os-release` OR `sw_vers`): 
- Kernel (e.g. `uname -a`): 
- Others:

**Comment by SAPJonasZengerle** [comment]
Currently, the following (manual) commands should do the trick:
```
helm delete karydia --purge &&
kubectl delete mutatingwebhookconfigurations karydia-webhook &&
kubectl delete validatingwebhookconfigurations karydia-webhook &&
kubectl delete customresourcedefinitions karydianetworkpolicies.karydia.gardener.cloud &&
kubectl delete customresourcedefinitions karydiaconfigs.karydia.gardener.cloud
```
