### ISSUE TITLE
Move Karydia to namespace karydia

### ISSUE THREAD

**Issue by CodeClinch** [karydia/karydia#196]
### Description

Karydia should not run in namespace kube-system.

### User Story

As _an administrator_ I want to _run Karydia in an own namespace_ in order to _have a clear separation_.

**Comment by Neumann-Nils** [comment]
To-Do:
- [ ] Create namespace `karydia` at start of installation
- [ ] Check pull request that annotate namespace (exclude `karydia` namespace)
