### ISSUE TITLE
Helm v2 not compatible with Kubernetes 1.16

### ISSUE THREAD

**Issue by Neumann-Nils** [karydia/karydia#223]
### Description
You can not install karydia with a cluster running Kubernetes 1.16.

This bug is known to the Helm developers and is fixed. The release of this bug fix will be included in Helm 2.15 (release planned for October 16th).

More information in the respective PR:
https://github.com/helm/helm/pull/6462#issuecomment-537482539

**Comment by linuxbsdfreak** [comment]
@Neumann-Nils . I have upgraded the helmv2 client/tiller on K8s 1.16. However following  install/charts/templates/deployment.yaml has to be changed to get it working

1.  Changed the apiVersion
```
-apiVersion: extensions/v1beta1
+apiVersion: apps/v1
```
2. Added the following under spec 

```
 spec:
+  selector:
+    matchLabels:
+      app: {{ .Values.metadata.labelApp }}
```

**Comment by Neumann-Nils** [comment]
Thanks for the feedback. As the Helm `2.15` release is official, we will also support it and therefore also support Kubernetes `1.16`.
