### ISSUE TITLE
Deployment Version is not supported

### ISSUE THREAD

**Issue by CodeClinch** [karydia/karydia#232]
### Description

After update of helm locally, the installation is not working anymore. 

Error: validation failed: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"

### Steps to reproduce
brew upgrade
$ helm install ./install/charts --name karydia --namespace karydia

Error: validation failed: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"

### Expected behavior
Installed latest version of Karydia

### Environment

- Kubernetes version (use `kubectl version`): 
- Cloud provider or hardware configuration: 
- [x] Gardener cluster
- OS (e.g. `cat /etc/os-release` OR `sw_vers`): 
- Kernel (e.g. `uname -a`): 
- Others:

**Comment by Neumann-Nils** [comment]
Probably connected with #223 and Helm 2.15.

**Comment by Neumann-Nils** [comment]
Tested it with the following results. Installation works fine with Helm `2.13`/`2.15` and a Cluster running Kubernetes `1.15.5`. I encountered the same problems (as described in the issue) when using Helm `2.15` and a cluster running `1.16.2`.
