### ISSUE TITLE
App Hub Integration is not working

### ISSUE THREAD

**Issue by CodeClinch** [karydia/karydia#246]
### Description

Deploy Karydia through App Hub into a Gardener Cluster. The deployed Karydia Pod is running in default namespace but not working.

### Expected behavior

Karydia should run in namespace karydia 
Karydia should add seccomp, ...

### Logs / console output / screenshots / affected lines of code

![image](https://user-images.githubusercontent.com/40203931/72139531-52294e00-338f-11ea-97d5-f889596fe052.png)

![image](https://user-images.githubusercontent.com/40203931/72139559-581f2f00-338f-11ea-8880-529cf0c49419.png)

### Environment

- Kubernetes version (use `kubectl version`): 
- Cloud provider or hardware configuration: 
- [x] Gardener cluster
- OS (e.g. `cat /etc/os-release` OR `sw_vers`): 
- Kernel (e.g. `uname -a`): 
- Others:

**Comment by Neumann-Nils** [comment]
Need some more input on this problem. First guess, the installation does not use the `namespace` cli flag (as described in [docs](https://github.com/karydia/karydia/tree/master/install)).

**Comment by ThormaehlenFred** [comment]
Hi Nils, you can try it by your own: Please create a secret and cluster in dev https://dashboard.garden.dev.k8s.ondemand.com/namespace/garden-karydiatst/shoots/
and then deploy Karydia via the helm chart which is used in the app hub.

**Comment by Neumann-Nils** [comment]
Created PR for integrating Karydia correctly into the App Hub (https://github.tools.sap/kubernetes/charts/pull/22).
