### ISSUE TITLE
HA deployments with pod disruption budget

### ISSUE THREAD

**Issue by rfranzke** [karydia/karydia#251]
### Description
The Karydia Helm chart hard-codes `1` replica. As it registers webhooks that trigger for `pods` on `CREATE`/`UPDATE` operations, once the single Karydia pod is deleted, the system can never recover itself automatically.
Webhooks on CREATE/UPDATE for pods is dangerous in general if the server runs inside the cluster itself. So, what you should at least do is deploy the webhook server in high-availability mode (>= 3 replicas with pod anti-affinity) and with pod disruption budgets to ensure that at least one server is always reachable (to allow recreating the others).

**Comment by Neumann-Nils** [comment]
Thanks for your detailed issue and especially the suggestions to fix this problem. Could you give feedback on #253?
