### ISSUE TITLE
Deny Cluster Egress Traffic by Default

### ISSUE THREAD

**Issue by marwinski** [karydia/karydia#31]
The goal of several common attacks on infrastructure providers are bitcoin mining and sending spam mail. For both scenarios egress traffic is required. 

The idea is to add a network policy to explicitly deny egress traffic for deployed pods (cluster internal traffic is ok). Most pods do not need to talk to resources on the internet anyway. 

This limitation could be lifted with a simple label: `allowEgress: "true"`. In addition this could be set on the namespace to have it configured for all pods.

**Comment by Neumann-Nils** [comment]
Closed in favor of #46, as it describes the problem from a broader point of view.
