### ISSUE TITLE
Simple Karydia Installation Option

### ISSUE THREAD

**Issue by marwinski** [karydia/karydia#58]
## Story

As a user I want to have a simple installation option and not a multi-stage manual process.

## Implementation Proposal

helm appears to be the natural installation option. In addition some scripts will be required to generate the certificates and include them into the ```values.yaml``` file. 

If not too complex we can ask the user to install the tools locally (although the tools are even a challenge on a Mac). Easier would be a container 

```
docker run karydia/karydia-configure -v .:/config
```

**Comment by Neumann-Nils** [comment]
Helm seems to be the natural installation option. However, it seems quite difficult to integrate the karydia installation process into the helm framework.

While I had a look at helm, I could not find a way to run local scripts within the helm installation process. The only option might be to use hooks (https://github.com/helm/helm/blob/master/docs/charts_hooks.md), which spin up a pod and run certain commands and scripts within this pod. However, I could not get the whole installation process running. At the end, I settled with the following problems:
- In general, it seems cumbersome to get kubectl configured and execute the needed commands from within the pod
- "pre-install" hooks cannot use volume mounts, as they are loaded after these hooks are initiated


In general, it could be possible to get a karydia installation running using only helm. However, other options seems more trivial and in the end may be equally user-friendly. Thus, I suggest two different options to consider:
- Create a bash script that runs the karydia installation, while making use of helm for the manifests (this would not work on Windows)
- Put everything together into a docker image and automate the installation in this way

**Comment by marwinski** [comment]
We use bash and/or python ad/or spiff++ for creating the Values.yaml files. Agreed this is hard to do with helm and not really useful. I think short term a script is absolutely fine that creates the values.yaml. A container is nice to have (and not all that difficult). It will also be useful when we have a controller to automatically install Karydia.
