### ISSUE TITLE
component_descriptor

### ISSUE THREAD

**Issue by ThormaehlenFred** [karydia/karydia#60]
A component_descriptor file is required for adding Karydia into CI/CD processes see the [Documentation](https://gardener.github.io/cc-utils/traits/component_descriptor.html) as it was done already with most of the Gardener repos

**Comment by ccwienk** [comment]
please note that you will also have to add the traits:
- [release](https://gardener.github.io/cc-utils/traits/release.html) trait in order to create releases
- [component_descriptor](https://gardener.github.io/cc-utils/traits/component_descriptor.html)

**Comment by dacappo** [comment]
I created a relase job for master with both traits included (2f784d341642638de3d05ec3dcf214d1feee2e86).
