### ISSUE TITLE
scripts/create-karydia-tls-secret: error: unable to decode "STDIN"

### ISSUE THREAD

**Issue by thkukuk** [karydia/karydia#76]
I tried to use karydia on openSUSE Kubic, but failed with the scripts/create-karydia-tls-secret script (kubectl 1.13.4).

The error I get is:
error: error validating "STDIN": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false

If you disable validation, it will of course fail with kind not set.

**Comment by dacappo** [comment]
Hi @thkukuk, it seems that the `kubectl apply` at the end of the script is failing. Can you provide the intermediate result of the `kubectl create secret generic` which is piped into the `kubectl apply` (just comment out the `|` and the last line). Are the server and client version given by `kubectl` both 1.13.4?

Best,
Patrick

**Comment by thkukuk** [comment]
Server and client are both 1.13.4.

The output is:

data:
  cert.pem: LS0...
  key.pem: LS0...
metadata:
  creationTimestamp: null
  name: karydia-tls

**Comment by SAPJonasZengerle** [comment]
Hi @thkukuk, thanks for opening an issue for that.

We (our team), only focused at plain [Kubernetes](https://kubernetes.io/docs/setup/) and [Gardener Kubernetes](https://gardener.cloud/) clusters till now. Thus, we don't know the [openSUSE Kubic](https://kubic.opensuse.org/) project in detail.

A first quick look lets me tend to some idiosyncrasies of [openSUSE Kubic](https://kubic.opensuse.org/) but this is just an uneducated guess.

Do you have some more knowledge with [openSUSE Kubic](https://kubic.opensuse.org/) and maybe already know what the problem could be? If yes, we would be more than happy if you could provide a pull request to fix this. If no, it would be great if you could provide us as much information regarding this issue as possible (e.g. [openSUSE Kubic](https://kubic.opensuse.org/) version, cloud provider or hardware configuration, OS (e.g. `cat /etc/os-release`), Kernel (e.g. `uname -a`), ...).

Best regards,
Jonas

**Comment by thkukuk** [comment]
Ok, found the problem: kubectl 1.13.x does not create a correct yaml file which it could apply afterwards, kubectl 1.14.0 does this. So this is now working, maybe a hint that at minimum kubectl 1.14.0 is required would be helpful.

**Comment by SAPJonasZengerle** [comment]
Thanks for further investigating this issue! It's great to hear that it's now working for you!!
